from . import optical_config
from . import account_move
from . import account_move_ext
from . import optical_branch_ext
from . import optical_dashboard
from . import optical_insurance
from . import optical_insurance_ext
from . import optical_insurance_payment
from . import optical_optician_ext
from . import optical_patient
from . import optical_settings
from . import optical_test
from . import optical_test_ext
from . import pos_config
from . import pos_config_ext
from . import pos_order
from . import pos_order_ext
from . import pos_payment_ext
from . import pos_payment_method_ext
from . import pos_session_ext
from . import res_config_settings
from . import res_partner_optical
from . import res_partner_pos_ext
from . import stock_location_ext
