{
    "name": "BP Optical Solution",
    "version": "17.0.1.0.0",
    "category": "Medical/Optical",
    "summary": "Standalone optical suite with core, POS, and POS invoice payment features.",
    "author": "Blackpaw Innovations",
    "website": "https://www.blackpawinnovations.com",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "mail",
        "product",
        "account",
        "calendar",
        "point_of_sale",
        "stock",
    ],
    "data": [
        "security/bp_optical_core_security.xml",
        "security/bp_optical_pos_security.xml",
        "security/optical_record_rules.xml",
        "security/ir.model.access.csv",
        "data/optical_sequence.xml",
        "data/optical_stages.xml",
        "data/optical_cron.xml",
        "data/insurance_journal.xml",
        "data/product_data.xml",
        "views/menu_views.xml",
        "views/optical_appointment_views.xml",
        "views/optical_sales_views.xml",
        "views/optical_insurance_views.xml",
        "views/optical_test_views.xml",
        "views/optical_patient_views.xml",
        "views/optical_config_views.xml",
        "views/optical_lens_config_views.xml",
        "views/res_partner_optical_views.xml",
        "views/optical_settings_views.xml",
        "views/optical_dashboard_views.xml",
        "views/optical_branch_views.xml",
        "views/optical_optician_views.xml",
        "views/pos_optical_menu_views.xml",
        "views/pos_config_optical_views.xml",
        "views/stock_location_views.xml",
        "views/pos_payment_method_views.xml",
        "views/account_move_insurance_views.xml",
        "views/account_move_views.xml",
        "views/pos_config_views.xml",
        "views/pos_order_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/optical_branch_pl_wizard_views.xml",
        "views/customer_statement_views.xml",
        "views/customer_statement_report.xml",
        "report/prescription_report.xml",
        "report/patient_report.xml",
        "report/prescription_report_compact_backup.xml",
        "report/pending_insurance_report.xml",
        "report/optical_branch_pl_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "BP_Optical_solution/static/src/css/optical_dashboard.css",
            "BP_Optical_solution/static/src/xml/optical_dashboard.xml",
            "BP_Optical_solution/static/src/js/optical_dashboard.js",
        ],
        "point_of_sale._assets_pos": [
            "BP_Optical_solution/static/src/js/optical_insurance_popup.js",
            "BP_Optical_solution/static/src/js/insurance_popup.js",
            "BP_Optical_solution/static/src/js/insurance_payment_selection_popup.js",
            "BP_Optical_solution/static/src/js/insurance_form_popup.js",
            "BP_Optical_solution/static/src/js/optical_test_popup.js",
            "BP_Optical_solution/static/src/js/optical_test_button.js",
            "BP_Optical_solution/static/src/js/optical_models_ext.js",
            "BP_Optical_solution/static/src/js/partner_editor_ext.js",
            "BP_Optical_solution/static/src/js/partner_optical_history.js",
            "BP_Optical_solution/static/src/js/stage_change_popup.js",
            "BP_Optical_solution/static/src/js/test_stage_button.js",
            "BP_Optical_solution/static/src/js/test_view_popup.js",
            "BP_Optical_solution/static/src/js/InvoicePaymentButton.js",
            "BP_Optical_solution/static/src/js/InvoicePaymentPopup.js",
            "BP_Optical_solution/static/src/js/pos_order_invoice_payment.js",
            "BP_Optical_solution/static/src/xml/optical_insurance_popup.xml",
            "BP_Optical_solution/static/src/xml/optical_test_popup.xml",
            "BP_Optical_solution/static/src/xml/optical_test_button.xml",
            "BP_Optical_solution/static/src/xml/insurance_popup.xml",
            "BP_Optical_solution/static/src/xml/insurance_payment_selection_popup.xml",
            "BP_Optical_solution/static/src/xml/insurance_form_popup.xml",
            "BP_Optical_solution/static/src/xml/partner_editor_ext.xml",
            "BP_Optical_solution/static/src/xml/partner_optical_history.xml",
            "BP_Optical_solution/static/src/xml/stage_change_popup.xml",
            "BP_Optical_solution/static/src/xml/test_stage_button.xml",
            "BP_Optical_solution/static/src/xml/test_view_popup.xml",
            "BP_Optical_solution/static/src/xml/InvoicePaymentPopup.xml",
            "BP_Optical_solution/static/src/xml/InvoicePaymentReceipt.xml",
        ],
    },
    "images": ["BP_Optical_solution/static/description/icon.png"],
    "application": True,
    "installable": True,
}
